services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - my-network
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development

  redis:
    image: redis:latest
    networks:
      - my-network
    ports:
      - "6379:6379"

networks:
  my-network:
    driver: bridge
